@database = BigBoxStore
@collection = GroceryInventory
@domain = http://localhost
@port = 3000
###
GET {{domain}}:{{port}}/find/{{database}}/{{collection}}
Content-Type: application/json

###
POST {{domain}}:{{port}}/insert/{{database}}/{{collection}}
Content-Type: application/json

{
  "document":  {
    "item": "pizza",
    "food_group": "",
    "price_in_usd": 2.9,
    "quantity": 68,
    "calories_per_100g": 220
  }
}

###
@id = 6723f33595e6d06a4bf4d7bd
DELETE {{domain}}:{{port}}/delete/{{database}}/{{collection}}/{{id}}
Content-Type: application/json